services:
  db:
    image: postgres:14.2
    ports:
      - '5432:5432'
    volumes:
      - 'lunch-together-postgres:/var/modules/lunch-together/postgresql'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - "met-redis:/data"
  rabbitmq:
    image: rabbitmq:3.12
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - "rabbitmq:/var/lib/rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  identity-service:
    build:
      context: .
      dockerfile: ./apps/identity/dockerfile
    ports:
      - "3001:3001"
      - "3011:3011"
    env_file:
      - ./apps/identity/src/.env.prod
  group-service:
    build:
      context: .
      dockerfile: ./apps/group/dockerfile
    ports:
      - "3002:3002"
      - "3012:3012"
    env_file:
      - ./apps/group/src/.env.prod
  meeting-service:
    build:
      context: .
      dockerfile: ./apps/meeting/dockerfile
    ports:
      - "3003:3003"
      - "3013:3013"
    env_file:
      - ./apps/meeting/src/.env.prod
    depends_on:
      - rabbitmq
  socket-service:
    build:
      context: .
      dockerfile: ./apps/socket/dockerfile
    ports:
      - "3004:3004"
      - "80:80"
    env_file:
      - ./apps/socket/src/.env.prod
    depends_on:
      - rabbitmq
  graphql-gateway-service:
    build:
      context: .
      dockerfile: ./apps/graphql-gateway/dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./apps/graphql-gateway/src/.env.prod
    depends_on:
      - identity-service
      - group-service
      - meeting-service
volumes:
  lunch-together-postgres:
  met-redis:
  rabbitmq:
