# Use a smaller base image for Node.js
FROM node:18.17.0

# Set the working directory in the container
WORKDIR /app/identity

COPY . .

# Install only production dependencies
RUN npm install

COPY /prisma/user/.env.prod prisma/user/.env

RUN npm run prisma:migrate-deploy prisma/user/schema.prisma  

# Install only production dependencies
RUN npm run build identity

# Expose the port your NestJS application is listening on
EXPOSE 3001 3011

# Define the command to run the NestJS application
CMD ["node", "dist/apps/identity/main.js"]
# CMD [ "ls", '-a' ]
