# Use a smaller base image for Node.js
FROM node:18.17.0

# Set the working directory in the container
WORKDIR /app/group

COPY . .

# Install only production dependencies
RUN npm install

RUN npm run prisma:migrate-deploy prisma/group/schema.prisma  

RUN npx prisma generate --schema prisma/group/schema.prisma

# Install only production dependencies
RUN npm run build group

# Expose the port your NestJS application is listening on
EXPOSE 3002 3012

# Define the command to run the NestJS application
CMD ["node", "dist/apps/group/main.js"]
