# Use a smaller base image for Node.js
FROM node:18.17.0

# Set the working directory in the container
WORKDIR /app/meeting

COPY . .

# Install only production dependencies
RUN npm install

RUN npm run prisma:migrate-deploy prisma/meeting/schema.prisma  

RUN npx prisma generate --schema prisma/meeting/schema.prisma

# Install only production dependencies
RUN npm run build meeting

# Expose the port your NestJS application is listening on
EXPOSE 3003 3013

# Define the command to run the NestJS application
CMD ["node", "dist/apps/meeting/main.js"]
