# Use a smaller base image for Node.js
FROM node:18.17.0

# Set the working directory in the container
WORKDIR /app/socket

COPY . .

# Install only production dependencies
RUN npm install

# Install only production dependencies
RUN npm run build socket

# Expose the port your NestJS application is listening on
EXPOSE 3004 80

# Define the command to run the NestJS application
CMD ["node", "dist/apps/socket/main.js"]
