# Use a smaller base image for Node.js
FROM node:18.17.0

# Set the working directory in the container
WORKDIR /app/socket

WORKDIR /met

COPY ./apps/socket ./apps/socket
COPY ./libs/meeting ./libs/meeting
COPY ./libs/shared ./libs/shared
COPY ./prisma/meeting ./prisma/meeting
COPY ./nest-cli.json .
COPY ./package.json .
COPY ./package-lock.json .
COPY ./tsconfig.json .
COPY ./tsconfig.build.json .

RUN npm install

RUN npm run prisma:generate --schema prisma/meeting/schema.prisma

RUN npm run build socket

# Expose the port your NestJS application is listening on
EXPOSE 3004 80

# Define the command to run the NestJS application
CMD ["node", "dist/apps/socket/main.js"]
